import PDFDocument from 'pdfkit'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import config from '../config.js'
import { getSettings } from '../services/settingsService.js'

const PDF_DIR = () => path.join(config.uploadPath, 'pdfs')

/**
 * Render a markdown-ish document body to a branded PDF on disk.
 * Generated PDFs contain PII — they live under the upload path and are only
 * served behind auth, never statically.
 * @param {{title:string, subtitle?:string, body:string, footer?:string}} doc
 * @returns {Promise<string>} stored filename (non-guessable)
 */
export async function renderPdf (doc) {
  const settings = getSettings()
  fs.mkdirSync(PDF_DIR(), { recursive: true })
  const filename = crypto.randomBytes(16).toString('hex') + '.pdf'
  const filePath = path.join(PDF_DIR(), filename)
  const primary = settings.brand_primary_color || '#2563eb'

  const pdf = new PDFDocument({ size: 'A4', margins: { top: 60, bottom: 60, left: 56, right: 56 } })
  const stream = fs.createWriteStream(filePath)
  pdf.pipe(stream)

  const logoPath = settings.logo_filename ? path.join(config.uploadPath, 'logos', settings.logo_filename) : null
  if (logoPath && fs.existsSync(logoPath)) {
    try { pdf.image(logoPath, 56, 40, { height: 36 }) } catch { /* unsupported image format */ }
    pdf.moveDown(2)
  }
  pdf.fillColor(primary).fontSize(20).font('Helvetica-Bold').text(settings.business_name || 'CareLane', { align: 'left' })
  const contact = [settings.abn ? `ABN ${settings.abn}` : null, settings.business_phone, settings.business_email, settings.business_address]
    .filter(Boolean).join('  ·  ')
  if (contact) pdf.fillColor('#666666').fontSize(9).font('Helvetica').text(contact)
  pdf.moveDown(1)
  pdf.fillColor('#111111').fontSize(16).font('Helvetica-Bold').text(doc.title)
  if (doc.subtitle) pdf.fillColor('#444444').fontSize(11).font('Helvetica').text(doc.subtitle)
  pdf.moveDown(1)

  renderMarkdown(pdf, doc.body || '')

  pdf.moveDown(2)
  pdf.fillColor('#888888').fontSize(8).text(doc.footer || `Generated by CareLane on ${new Date().toISOString().slice(0, 10)}`)
  pdf.end()

  await new Promise((resolve, reject) => {
    stream.on('finish', resolve)
    stream.on('error', reject)
  })
  return filename
}

/**
 * Minimal markdown renderer for pdfkit (headings, bullets, bold paragraphs).
 * @param {PDFDocument} pdf
 * @param {string} markdown
 */
function renderMarkdown (pdf, markdown) {
  const lines = markdown.split('\n')
  for (const raw of lines) {
    const line = raw.trimEnd()
    const plain = t => t.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/`(.+?)`/g, '$1')
    if (/^###\s+/.test(line)) {
      pdf.moveDown(0.5).fillColor('#222222').fontSize(11).font('Helvetica-Bold').text(plain(line.replace(/^###\s+/, '')))
    } else if (/^##\s+/.test(line)) {
      pdf.moveDown(0.7).fillColor('#222222').fontSize(13).font('Helvetica-Bold').text(plain(line.replace(/^##\s+/, '')))
    } else if (/^#\s+/.test(line)) {
      pdf.moveDown(0.8).fillColor('#111111').fontSize(15).font('Helvetica-Bold').text(plain(line.replace(/^#\s+/, '')))
    } else if (/^\s*[-*]\s+/.test(line)) {
      pdf.fillColor('#222222').fontSize(10).font('Helvetica').text('•  ' + plain(line.replace(/^\s*[-*]\s+/, '')), { indent: 12 })
    } else if (line === '') {
      pdf.moveDown(0.4)
    } else {
      pdf.fillColor('#222222').fontSize(10).font('Helvetica').text(plain(line))
    }
  }
}

/**
 * Absolute path of a rendered PDF, for auth-gated download routes.
 * @param {string} filename
 */
export function pdfPath (filename) {
  return path.join(PDF_DIR(), filename)
}
