import PDFDocument from 'pdfkit'
import { marked } from 'marked'
import sharp from 'sharp'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import config from '../config.js'
import { getSettings } from '../services/settingsService.js'

const PDF_DIR = () => path.join(config.uploadPath, 'pdfs')

const FONT = {
  normal: 'Helvetica',
  bold: 'Helvetica-Bold',
  italic: 'Helvetica-Oblique',
  boldItalic: 'Helvetica-BoldOblique',
  mono: 'Courier'
}
const INK = '#222222'
const MUTED = '#555555'
const CODE_COLOR = '#9333ea'

/**
 * Render a markdown document body to a branded PDF on disk.
 * Generated PDFs contain PII — they live under the upload path and are only
 * served behind auth, never statically.
 * @param {{title:string, subtitle?:string, body:string, footer?:string}} doc
 * @returns {Promise<string>} stored filename (non-guessable)
 */
export async function renderPdf (doc) {
  const settings = getSettings()
  fs.mkdirSync(PDF_DIR(), { recursive: true })
  const filename = crypto.randomBytes(16).toString('hex') + '.pdf'
  const filePath = path.join(PDF_DIR(), filename)
  const primary = settings.brand_primary_color || '#2563eb'

  const pdf = new PDFDocument({ size: 'A4', margins: { top: 60, bottom: 60, left: 56, right: 56 } })
  const stream = fs.createWriteStream(filePath)
  pdf.pipe(stream)

  const logoBuffer = await loadLogo(settings.logo_filename)
  if (logoBuffer) {
    try {
      pdf.image(logoBuffer, 56, 40, { fit: [150, 40], align: 'left' })
      pdf.y = 92
    } catch { /* unrenderable logo — fall back to the text header */ }
  }
  pdf.fillColor(primary).fontSize(20).font(FONT.bold).text(settings.business_name || 'CareLane', { align: 'left' })
  const contact = [settings.abn ? `ABN ${settings.abn}` : null, settings.business_phone, settings.business_email, settings.business_address]
    .filter(Boolean).join('  ·  ')
  if (contact) pdf.fillColor('#666666').fontSize(9).font(FONT.normal).text(contact)
  pdf.moveDown(1)
  pdf.fillColor('#111111').fontSize(16).font(FONT.bold).text(doc.title)
  if (doc.subtitle) pdf.fillColor('#444444').fontSize(11).font(FONT.normal).text(doc.subtitle)
  pdf.moveDown(1)

  renderMarkdown(pdf, doc.body || '')

  pdf.moveDown(2)
  pdf.fillColor('#888888').fontSize(8).font(FONT.normal).text(doc.footer || `Generated by CareLane on ${new Date().toISOString().slice(0, 10)}`)
  pdf.end()

  await new Promise((resolve, reject) => {
    stream.on('finish', resolve)
    stream.on('error', reject)
  })
  return filename
}

/**
 * Load the business logo as a PNG buffer pdfkit can embed.
 * pdfkit only understands PNG/JPEG, so SVG/WebP logos are rasterised via sharp.
 * @param {string} [logoFilename]
 * @returns {Promise<Buffer|null>}
 */
// Cache the rasterised logo keyed by filename+mtime so we don't re-run sharp on
// every PDF render (the logo changes rarely; rasterising an SVG is non-trivial).
let logoCache = null
async function loadLogo (logoFilename) {
  if (!logoFilename) return null
  // basename guards against a traversal value ever reaching the filesystem,
  // even though logo_filename is only ever set via the upload endpoint.
  const logoPath = path.join(config.uploadPath, 'logos', path.basename(logoFilename))
  let stat
  try { stat = fs.statSync(logoPath) } catch { return null }
  const cacheKey = `${logoPath}:${stat.mtimeMs}`
  if (logoCache?.key === cacheKey) return logoCache.buffer
  try {
    const buffer = await sharp(logoPath, { density: 288 })
      .resize({ width: 600, height: 160, fit: 'inside', withoutEnlargement: true })
      .png()
      .toBuffer()
    logoCache = { key: cacheKey, buffer }
    return buffer
  } catch {
    return null
  }
}

/**
 * Render a markdown string into the PDF using marked's block lexer so that
 * headings, emphasis, ordered/unordered (and nested) lists, blockquotes,
 * code blocks, tables and rules all render correctly.
 * @param {PDFDocument} pdf
 * @param {string} markdown
 */
function renderMarkdown (pdf, markdown) {
  // breaks: true so a single newline becomes a hard line break, matching how
  // authors lay out agreements/reports line-by-line rather than collapsing them.
  const tokens = marked.lexer(markdown || '', { gfm: true, breaks: true })
  for (const token of tokens) renderBlock(pdf, token, 0)
}

/**
 * Render a single block-level markdown token.
 * @param {PDFDocument} pdf
 * @param {object} token
 * @param {number} depth list nesting depth
 */
function renderBlock (pdf, token, depth) {
  switch (token.type) {
    case 'heading': {
      const size = token.depth <= 1 ? 15 : token.depth === 2 ? 13 : 11
      pdf.moveDown(token.depth <= 2 ? 0.7 : 0.5)
      writeRich(pdf, token.tokens, { fontSize: size, color: '#111111', baseFont: FONT.bold })
      break
    }
    case 'paragraph':
      writeRich(pdf, token.tokens, { fontSize: 10, color: INK })
      pdf.moveDown(0.35)
      break
    case 'list':
      renderList(pdf, token, depth)
      if (depth === 0) pdf.moveDown(0.3)
      break
    case 'blockquote':
      pdf.moveDown(0.2)
      for (const inner of token.tokens) {
        if (inner.type === 'paragraph') {
          writeRich(pdf, inner.tokens, { fontSize: 10, color: MUTED, indent: 14, baseFont: FONT.italic })
          pdf.moveDown(0.3)
        } else {
          renderBlock(pdf, inner, depth)
        }
      }
      pdf.moveDown(0.2)
      break
    case 'code':
      pdf.moveDown(0.2).fillColor(MUTED).fontSize(9).font(FONT.mono)
      pdf.text(token.text || '', { indent: 12 })
      pdf.moveDown(0.3)
      break
    case 'table':
      renderTable(pdf, token)
      break
    case 'hr':
      pdf.moveDown(0.4)
      pdf.strokeColor('#dddddd').lineWidth(1)
        .moveTo(pdf.x, pdf.y).lineTo(pdf.page.width - pdf.page.margins.right, pdf.y).stroke()
      pdf.moveDown(0.5)
      break
    case 'space':
      pdf.moveDown(0.4)
      break
    default:
      if (token.tokens) writeRich(pdf, token.tokens, { fontSize: 10, color: INK })
      else if (token.text) pdf.fillColor(INK).fontSize(10).font(FONT.normal).text(token.text)
  }
}

/**
 * Render an ordered/unordered list, recursing into nested lists.
 * @param {PDFDocument} pdf
 * @param {object} list marked list token
 * @param {number} depth
 */
function renderList (pdf, list, depth) {
  let index = Number.isFinite(list.start) && list.start ? Number(list.start) : 1
  for (const item of list.items) {
    const prefix = list.ordered ? `${index}.  ` : '•  '
    const indent = 14 + depth * 16
    let prefixUsed = false
    for (const block of item.tokens || []) {
      if (block.type === 'list') {
        renderList(pdf, block, depth + 1)
        continue
      }
      const inline = block.tokens || [{ type: 'text', text: block.text || '' }]
      writeRich(pdf, inline, {
        fontSize: 10,
        color: INK,
        indent: prefixUsed ? indent + 14 : indent,
        prefix: prefixUsed ? null : prefix
      })
      prefixUsed = true
    }
    if (!prefixUsed) writeRich(pdf, [], { fontSize: 10, color: INK, indent, prefix })
    if (list.ordered) index++
  }
}

/**
 * Render a markdown table as plain rows (pdfkit has no native table support).
 * @param {PDFDocument} pdf
 * @param {object} table marked table token
 */
function renderTable (pdf, table) {
  pdf.moveDown(0.2)
  const cellText = (cell) => (cell.tokens ? cell.tokens.map((t) => t.text || '').join('') : cell.text || '')
  const header = table.header.map(cellText).join('   |   ')
  pdf.fillColor('#111111').fontSize(10).font(FONT.bold).text(header)
  pdf.strokeColor('#dddddd').lineWidth(0.7).moveTo(pdf.x, pdf.y).lineTo(pdf.page.width - pdf.page.margins.right, pdf.y).stroke()
  pdf.moveDown(0.1)
  for (const row of table.rows) {
    pdf.fillColor(INK).fontSize(10).font(FONT.normal).text(row.map(cellText).join('   |   '))
  }
  pdf.moveDown(0.4)
}

/**
 * Flatten marked inline tokens into styled text runs.
 * @param {object[]} tokens
 * @param {{bold:boolean, italic:boolean}} state
 * @returns {{text:string, bold:boolean, italic:boolean, code:boolean}[]}
 */
function inlineSegments (tokens, state = { bold: false, italic: false }) {
  const out = []
  for (const t of tokens || []) {
    if (t.type === 'strong') out.push(...inlineSegments(t.tokens, { ...state, bold: true }))
    else if (t.type === 'em') out.push(...inlineSegments(t.tokens, { ...state, italic: true }))
    else if (t.type === 'del') out.push(...inlineSegments(t.tokens, state))
    else if (t.type === 'codespan') out.push({ text: t.text, ...state, code: true })
    else if (t.type === 'br') out.push({ br: true })
    else if (t.type === 'link') out.push(...(t.tokens ? inlineSegments(t.tokens, state) : [{ text: t.text, ...state, code: false }]))
    else if (t.tokens) out.push(...inlineSegments(t.tokens, state))
    // Collapse any stray newlines into spaces — real line breaks arrive as `br`
    // tokens; a newline left inside a `continued` run makes pdfkit overlap text.
    else out.push({ text: (t.text ?? t.raw ?? '').replace(/\s*\n\s*/g, ' '), ...state, code: false })
  }
  return out
}

/**
 * Write a run of inline tokens with bold/italic/code styling, optionally
 * prefixed (used for list bullets) and indented. Hard breaks split the run
 * into separate lines so pdfkit never has a newline inside a continued run.
 * @param {PDFDocument} pdf
 * @param {object[]} tokens inline tokens
 * @param {{fontSize:number, color:string, indent?:number, prefix?:string|null, baseFont?:string}} opts
 */
function writeRich (pdf, tokens, { fontSize, color, indent = 0, prefix = null, baseFont = null } = {}) {
  // Split the inline run into visual lines on hard breaks.
  const lines = [[]]
  for (const seg of inlineSegments(tokens)) {
    if (seg.br) { lines.push([]); continue }
    if (seg.text !== '') lines[lines.length - 1].push(seg)
  }
  pdf.fontSize(fontSize)

  lines.forEach((line, li) => {
    let started = false
    if (li === 0 && prefix) {
      const opts = { continued: true }
      if (indent) opts.indent = indent
      pdf.font(FONT.normal).fillColor(color).text(prefix, opts)
      started = true
    }
    if (line.length === 0) {
      // Empty line (blank paragraph or a leading/trailing break).
      if (started) pdf.text('')
      else pdf.font(baseFont || FONT.normal).fillColor(color).text(li === 0 ? '' : ' ')
      return
    }
    line.forEach((seg, i) => {
      const last = i === line.length - 1
      const font = seg.code ? FONT.mono
        : seg.bold && seg.italic ? FONT.boldItalic
          : seg.bold ? FONT.bold
            : seg.italic ? FONT.italic
              : (baseFont || FONT.normal)
      pdf.font(font).fillColor(seg.code ? CODE_COLOR : color)
      const opts = { continued: !last }
      if (indent && !started) opts.indent = indent
      pdf.text(seg.text, opts)
      started = true
    })
  })
}

/**
 * Absolute path of a rendered PDF, for auth-gated download routes.
 * @param {string} filename
 */
export function pdfPath (filename) {
  return path.join(PDF_DIR(), filename)
}

/**
 * Build a human-friendly, filesystem-safe download filename from a document
 * title (used for the Content-Disposition name so clients receive a file named
 * after the document rather than an internal id). Always ends in `.pdf`.
 * @param {string} title
 * @param {string} [fallback] used when the title is empty after cleaning
 * @returns {string}
 */
export function safeFilename (title, fallback = 'document') {
  const base = String(title || '')
    .replace(/[/\\?%*:|"<>]/g, '') // drop path/HTTP-unsafe characters
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120)
    .trim()
  return `${base || fallback}.pdf`
}
